Review15-PersonalProfolio/Controllers/BlogController.cs
using System.Dynamic;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Review15PersonalProfolio.Models;



namespace Review15PersonalProfolio.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public BlogController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult PostDisplayView(int id)
        {
            var thisPost = _db.Posts.Include(p => p.BlogResponces).Where(p => p.PostId == id).ToList();
            return View(thisPost);
        }


        public IActionResult BlogDisplayView()
        {


            var postWithResponceList = _db.Posts.Include(p => p.BlogResponces);
            if (_db.Responces != null)
            {
                List<Post> blogs = new List<Post> { };
                foreach(Post p in _db.Posts.Include(p => p.BlogResponces).ToList())
                {
                    p.GetBlurb();
                    blogs.Add(p);
                }

                return View(blogs);
            }
            else
            {
                var blogs = _db.Posts.ToList();
                return View(blogs);
            }

        }


        public IActionResult Create()
        {
          
            return View();
        }

        [HttpPost]
        public IActionResult Create(Post post)
        {
            _db.Posts.Add(post);
            _db.SaveChanges();
            return RedirectToAction("BlogDisplayView");
        }

        
        public IActionResult Delete()
        {
            ViewBag.PostId = new SelectList(_db.Posts, "PostId", "Title");
             return View();
        }

        [HttpPost]
        public IActionResult Delete(int PostId)
        {
            var idInput = PostId;
            var thisPost = _db.Posts.FirstOrDefault(p => p.PostId == PostId);
            _db.Posts.Remove(thisPost);
            _db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }
    }
}

Review15-PersonalProfolio/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Review15PersonalProfolio.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Review15PersonalProfolio.Controllers
{
    public class PictureController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public PictureController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public IActionResult Index()
        {
            var picsList = _db.Pictures.ToList();
            return View(picsList);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(Picture picture)
        {
            _db.Pictures.Add(picture);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete()
        {
            ViewBag.PictureId = new SelectList(_db.Pictures, "PictureId", "Url");
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int PictureId)
        {
            var thisPic = _db.Pictures.FirstOrDefault(p => p.PictureId == PictureId);
            _db.Pictures.Remove(thisPic);
            _db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }
    }
}

Review15-PersonalProfolio/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Review15PersonalProfolio</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Ian's PhakePholio</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="GetRepos">Git Repository</a></li>
                    <li><a asp-area="" asp-controller="Blog" asp-action="Index">Blog</a></li>
                    <li><a asp-area="" asp-controller="Picture" asp-action="Index">Pictures</a></li>
                    <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                 @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="" asp-action="">Logout</a></li>
                    }
                    else
                    {
                    <li><a asp-area="" asp-controller="" asp-action="">Login</a></li>
                    }
                 }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <div id="blog-body-view"></div>
        <div id="repo-body-view"></div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script type="text/javascript">

            $(document).ready(function () {
                
                $('.blog-display').click(function () {
                    $.ajax({
                        type: 'GET',
                        url: '@Url.Action("Blog","BlogDisplayView")',
                        success: function (result) {
                            $('#blog-body-view').html(result);

                        }
                    });
                });

                $('.repo-display').click(function () {
                    $.ajax({
                        type: 'GET',
                        url: '@Url.Action("Home","GetRepos")',
                        success: function (result) {
                            $('#repo-body-view').html(result);

                        }
                    });
                });

            });
        </script>
 
  

    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>