Review15-PersonalProfolio/Controllers/BlogController.cs
using System.Dynamic;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Review15PersonalProfolio.Models;



namespace Review15PersonalProfolio.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public BlogController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public IActionResult Index()
        {
           
            return View();
        }

        public IActionResult PostDisplayView(int id)
        {
            var thisPost = _db.Posts.Include(p => p.BlogResponces).Where(p => p.PostId == id).ToList();
            return View(thisPost);
        }


        public IActionResult BlogDisplayView()
        {


            var postWithResponceList = _db.Posts.Include(p => p.BlogResponces);
            if (_db.Responces != null)
            {
                List<Post> blogs = new List<Post> { };
                foreach(Post p in _db.Posts.Include(p => p.BlogResponces).ToList())
                {
                    p.GetBlurb();
                    blogs.Add(p);
                }

                return View(blogs);
            }
            else
            {
                var blogs = _db.Posts.ToList();
                return View(blogs);
            }

        }


        public IActionResult Create()
        {
          
            return View();
        }

        [HttpPost]
        public IActionResult Create(Post post)
        {
            _db.Posts.Add(post);
            _db.SaveChanges();
            return RedirectToAction("BlogDisplayView");
        }

        
        public IActionResult Delete()
        {
            ViewBag.PostId = new SelectList(_db.Posts, "PostId", "Title");
             return View();
        }

        [HttpPost]
        public IActionResult Delete(int PostId)
        {
            var idInput = PostId;
            var thisPost = _db.Posts.FirstOrDefault(p => p.PostId == PostId);
            _db.Posts.Remove(thisPost);
            _db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }
    }
}

Review15-PersonalProfolio/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Review15PersonalProfolio.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Review15PersonalProfolio.Controllers
{
    public class PictureController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public PictureController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public IActionResult Index()
        {
            var picsList = _db.Pictures.ToList();
            return View(picsList);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(Picture picture)
        {
            _db.Pictures.Add(picture);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete()
        {
            ViewBag.PictureId = new SelectList(_db.Pictures, "PictureId", "Url");
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int PictureId)
        {
            var thisPic = _db.Pictures.FirstOrDefault(p => p.PictureId == PictureId);
            _db.Pictures.Remove(thisPic);
            _db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }
    }
}

Review15-PersonalProfolio/Controllers/ResponceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Review15PersonalProfolio.Models;



namespace Review15PersonalProfolio.Controllers
{
    [Authorize]
    public class ResponceController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public ResponceController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        

        public IActionResult Create(int id, string title)
        {
            ViewBag.Id = id;
            ViewBag.PostTitle = title;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Responce responce)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var thisUser = _db.Users.FirstOrDefault(u => u.Id == userId);
            var profileName = thisUser.ProfileName;
            var postId = Int32.Parse(Request.Form["postId"]);
            var title = Request.Form["title"];
            var text = Request.Form["text"];
            Responce newResponce = new Responce(userId, profileName, postId, title, text);
            _db.Responces.Add(newResponce);
            _db.SaveChanges();
            return RedirectToAction ("BlogDisplayView", "Blog");

        }

        public IActionResult Delete()
        {
            ViewBag.ResponceId = new SelectList(_db.Responces, "ResponceId", "ResponceTitle");
            return View();
        }

        [HttpPost]
        public IActionResult Delete(int ResponceId)
        {
            var thisResponce = _db.Responces.FirstOrDefault(p => p.ResponceId == ResponceId);
            _db.Responces.Remove(thisResponce);
            _db.SaveChanges();
            return RedirectToAction("Index", "Admin");
        }
    }
}

Review15-PersonalProfolio/Views/Admin/Index.cshtml
<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
<link rel="stylesheet" href="~/css/site.css" />
<script type="text/javascript">

          $(document).ready(function () {
        $('.picture-create').click(function () {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("Create", "Picture")',
                success: function (result) {
                    $('#picture-create-view').html(result);

                }
            });
        });

               $('.picture-delete').click(function () {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Delete", "Picture")',
                    success: function (result) {
                    $('#picture-delete-view').html(result);

                    }
                    });
                    });


            $('.blog-create').click(function () {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Create", "Blog")',
                    success: function (result) {
                    $('#blog-create-view').html(result);

                    }
                    });
                    });

             $('.blog-delete').click(function () {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Delete", "Blog")',
                    success: function (result) {
                    $('#blog-delete-view').html(result);

                    }
                    });
              });

              $('.responce-delete').click(function () {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Delete", "Responce")',
                    success: function (result) {
                    $('#responce-delete-view').html(result);

                    }
                    });
                    });


 });
</script>

<body>
    <br />
    <div class="admin-panel">

        <div class="blog-create">
            <p class="blog-create">Create a new blog post</p>
        </div>
        <div class="blog-delete">
            <p class="blog-delete">Delete a blog post</p>
        </div>

        <div class="picture-create">
            <p>Add a new picture</p>
        </div>

        <div class="picture-delete">
            <p>Remove a picture</p>
        </div>

        <div class="responce-delete">
            <p class="responce-delete">Delete a responce</p>
        </div>

    </div>

    <div id="blog-create-view"></div>
    <div id="blog-delete-view"></div>
    <div id="picture-create-view"></div>
    <div id="picture-delete-view"></div>
    <div id="responce-delete-view"></div>

</body>